#!/usr/bin/env bash
#nginx must be nginx and must be listening on all port 8080

lsof -i:8080
chown nginx:nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
