#!/usr/bin/env bash
#nginx must be nginx and must be listening on all port 8080

lsof -i:8080
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
