#!/usr/bin/env bash
#make your fix short and sweet, 7 lines or shorter 
lsof -i:8080
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
