#!/usr/bin/env bash
# Install and configure HAProxy on loadbalancer server

sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 4812-web-01 34.234.90.21:80 check
        server 4812-web-02 52.91.90.202:80 check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
